import Picture from '@/components/common/Picture';
import UserAuthLayout from '@/components/layouts/UserAuthLayout';
import Head from 'next/head';
import React, { ReactElement } from 'react';
import { FaDownload } from 'react-icons/fa';

const UserOrderDetails = () => {
	return (
		<>
			<Head>
				<title>Order Details</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="user-order-details">
				<h3 className="user-page-title">
					Order No:
					<span className="text-[#6259CA] pl-2">6489436GF5</span>
				</h3>
				<table className="w-full border-collapse">
					<thead className="bg-[#F0F1FF] border border-[#F0F1FF]">
						<tr>
							<th className="text-left py-3 pl-3">Image</th>
							<th className="text-left py-3">Name</th>
							<th className="text-left py-3">Price</th>
							<th className="text-center py-3">QTY</th>
							<th className="text-center py-3 pr-3">Total</th>
						</tr>
					</thead>
					<tbody>
						{[1, 2, 3, 4, 5].map((item, index) => (
							<tr
								className="border border-[#F0F1FF] mb-2"
								style={{
									marginBottom: '10px',
								}}
								key={index}
							>
								<td className="py-2 pl-3">
									<Picture
										link={'/assets/user.jpg'}
										classList={
											'h-[45px] w-[45px] rounded-lg'
										}
										alt={''}
									/>
								</td>
								<td>Dr. Soiab Akhter</td>
								<td>$20.00</td>
								<td className="text-center">2</td>
								<td className="text-center">$20.00</td>
							</tr>
						))}
					</tbody>
				</table>
				<div className="flex justify-between items-end pt-5">
					<button className="submit__btn flex items-center gap-3">
						Get Invoice <FaDownload />
					</button>
					<div className="">
						<ul className="w-[300px]">
							<li className="flex items-center justify-between border-b py-4">
								<span className="order-details-info-label">
									Subtotal
								</span>
								<span className="order-details-info-value">
									$100.00
								</span>
							</li>
							<li className="flex items-center justify-between border-b py-4">
								<span className="order-details-info-label">
									Shipping
								</span>
								<span className="order-details-info-value">
									$20.00
								</span>
							</li>
							<li className="flex items-center justify-between py-4">
								<span className="order-details-info-label">
									Discount
								</span>
								<span className="order-details-info-value">
									0
								</span>
							</li>
							<li className="border-t-2 pt-4 flex items-center justify-between">
								<span className="text-lg font-semibold text-[#333]">
									Total
								</span>
								<span className="text-lg font-semibold text-[#333]">
									$20.00
								</span>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</>
	);
};
UserOrderDetails.getLayout = function getLayout(page: ReactElement) {
	return <UserAuthLayout>{page}</UserAuthLayout>;
};
export default UserOrderDetails;
