import CustomPagination from '@/components/common/CustomPagination';
import UserAuthLayout from '@/components/layouts/UserAuthLayout';
import { ReactElement, useState } from 'react';
import { HiEye } from 'react-icons/hi';
import { FaDownload } from 'react-icons/fa';
import Head from 'next/head';
import Link from 'next/link';

const Orders = () => {
	const [page, setPage] = useState(1);
	return (
		<>
			<Head>
				<title>Order list</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="user-orders">
				<h3 className="user-page-title">User Orders</h3>
				<table className="w-full border-collapse">
					<thead className="bg-[#F0F1FF] border border-[#F0F1FF]">
						<tr>
							<th className="text-left py-3 pl-3">Order No.</th>
							<th className="text-left py-3">Customer</th>
							<th className="text-left py-3">Email</th>
							<th className="text-left py-3">Status</th>
							<th className="text-left py-3">Items</th>
							<th className="text-left py-3">Total</th>
							<th className="text-center py-3 pr-3">Action</th>
						</tr>
					</thead>
					<tbody>
						{[1, 2, 3, 4, 5, 6, 7, 8, 9].map((item, index) => (
							<tr
								className="border border-[#F0F1FF] mb-2"
								style={{
									marginBottom: '10px',
								}}
								key={index}
							>
								<td className="py-2 pl-3">{`AB56H${index}`}</td>
								<td>Dr. Soiab Akhter</td>
								<td>abc@sample.com</td>
								<td>
									<span className="bg-green-300 text-[#000] text-sm py-1 px-2 rounded-md">
										Processing
									</span>
								</td>
								<td>20</td>
								<td>$20.00</td>
								<td className="pr-3">
									<div className="flex items-center gap-2 justify-center">
										<Link
											href="/user/orders/6489436GF5"
											className="action__view"
										>
											<HiEye className="text-[#000] text-base" />
										</Link>
										<button className="action__delete">
											<FaDownload className="text-[#000] text-base" />
										</button>
									</div>
								</td>
							</tr>
						))}
					</tbody>
				</table>
				<div className="flex items-center justify-end pt-8">
					<CustomPagination
						currentpage={2}
						totalPage={5}
						handler={setPage}
					/>
				</div>
			</div>
		</>
	);
};
Orders.getLayout = function getLayout(page: ReactElement) {
	return <UserAuthLayout>{page}</UserAuthLayout>;
};
export default Orders;
