import { yupResolver } from '@hookform/resolvers/yup';
import Head from 'next/head';
import { useForm } from 'react-hook-form';
import AuthFooter from '@/components/auth/AuthFooter';
import AuthHeader from '@/components/auth/AuthHeader';
import AuthInput from '@/components/auth/AuthInput';
import ButtonLoader from '@/components/common/ButtonLoader';
import { signupValidation } from '@/utils/validators';
import { useCreateData } from '@/hooks/useApi';
import { useRouter } from 'next/router';

const Register = () => {
	const signupTemplate = [
		{
			title: 'Name',
			name: 'name',
			type: 'text',
		},
		{
			title: 'Email',
			name: 'email',
			type: 'email',
		},
		{
			title: 'Password',
			name: 'password',
			type: 'password',
		},
	];

	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm({ resolver: yupResolver(signupValidation) });
	const { mutate: signup, isLoading } = useCreateData(
		'/api/auth/signup',
		'auth',
	);
	const router = useRouter();
	const onSubmit = handleSubmit((user) => {
		signup(user);
		setTimeout(() => {
			router.push('/admin/dashboard');
		}, 2000);
	});

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div id="auth" className="bg-[#EAEDF7]">
				<div className="container mx-auto font-mulish">
					<div className="h-screen flex items-center">
						<div className="lg:w-2/5 md:w-2/3 mx-auto bg-white p-12">
							<AuthHeader title="Register account" />
							<form onSubmit={onSubmit}>
								<AuthInput
									register={register}
									template={signupTemplate}
									errors={errors}
								/>
								<button
									className="btn-shadow w-full bg-[#6259CA] text-white uppercase text-base tracking-wider h-[48px] rounded"
									type="submit"
									disabled={isLoading}
								>
									{isLoading ? <ButtonLoader /> : 'Sign Up'}
								</button>
							</form>
							<AuthFooter
								text={'Already have account'}
								link={'/admin'}
								linkText={'Sign In'}
							/>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default Register;
