import TagField from '@/components/common/TagField';
import { ReactElement, useState } from 'react';
import DropdownSelector from '@/components/common/DropdownSelector';
import AdminAuthLayout from '../../components/layouts/AdminAuthLayout';
import Head from 'next/head';
const Dashboard = () => {
	const [tags, setTags] = useState<string[]>([]);

	return (
		<>
			<Head>
				<title>Dashboard - Welcome to admin dashboard</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
			</Head>
			<div>
				<h1 className="text-2xl text-black">I am Admin Dashboard</h1>
				<TagField defaultVal={tags} handler={setTags} />
				<DropdownSelector />
			</div>
		</>
	);
};
Dashboard.getLayout = function getLayout(page: ReactElement) {
	return <AdminAuthLayout>{page}</AdminAuthLayout>;
};
export default Dashboard;
